language: node_js
node_js:
  - '10'

before_install:
  - npm i -g npm@6.4.1

install:
  - npm install

cache:
  directories:
    - 'node_modules'

script:
  - npm test

before_deploy:
  - cd ..
  - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ${REPO}
  - git config --local user.name "${GITUSERNAME}"
  - git config --local user.email "${GITUSERMAIL}"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  # GitHub - Add zip to release
  - provider: releases
    api_key: ${GIT_API_KEY}
    file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
    skip_cleanup: true
