language: node_js
node_js:
  - '10'

before_install:
  - npm i -g npm@6.4.1

install:
  - npm install

cache:
  directories:
    - 'node_modules'

script:
  - npm test

before_deploy:
  - tar czvf build.tar.gz -C public .

deploy:
  # GitHub - Add zip to release
  - provider: releases
    api_key: ${GIT_API_KEY}
    file: "./build.tar.gz"
    skip_cleanup: true
    on:
      tags: true
      branch: master