language: node_js
node_js:
  - '10'

before_install:
  - npm i -g npm@6.4.1

install:
  - npm install

cache:
  directories:
    - 'node_modules'

script:
  - npm test

after_success:
  # Deploy to server using Puppet
  - wget -qO- https://pipelines.puppet.com/download/client | sh
  - echo "DistelliAccessToken: '$DistelliAccessToken'" >> ~/distelli.yml
  - echo "DistelliSecretKey: '$DistelliSecretKey'" >> ~/distelli.yml
  - /usr/local/bin/distelli login -conf ~/distelli.yml
  - /usr/local/bin/distelli deploy -q -y -m "Deployment from Travis-CI" --env dev

before_deploy:
  - tar -zcvf build.tar.gz public

deploy:
  # GitHub - Add zip to release
  - provider: releases
    api_key: ${GIT_API_KEY}
    file: "./build.tar.gz"
    skip_cleanup: true
    on:
      branch: master