if: branch = master
language: node_js
node_js:
  - '10'

before_install:
  - npm i -g npm@6.4.1

install:
  - npm install

cache:
  directories:
    - 'node_modules'

script:
  - npm test

after_success:
  - provider: script
    script: bash travis-scripts/deploy_to_puppet.sh
    skip_cleanup: true
    on:
      branch: master

before_deploy:
  - tar -zcvf build.tar.gz public

deploy:
  - provider: releases
    api_key: ${GIT_API_KEY}
    file: "./build.tar.gz"
    skip_cleanup: true
    on:
      branch: master